name: JMeter Test

on:
  push:
    branches:
      - main

jobs:
  run-jmeter-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2


    - name: Download and install JMeter
      run: |
        wget https://dlcdn.apache.org//jmeter/binaries/apache-jmeter-5.6.3.tgz
        tar -xf apache-jmeter-5.6.3.tgz

    - name: Install JMeter Plugins Manager
      run: |
        wget -O ${JMETER_HOME}/lib/ext/jmeter-plugins-manager-1.10.jar https://jmeter-plugins.org/get/
        ${JMETER_HOME}/bin/PluginsManagerCMD.sh install jpgc-casutg

    - name: Run JMeter Test
      run: |
        pwd
        ls
        ./apache-jmeter-5.6.3/bin/jmeter -n -t Gayan.jmx -l results.csv

    - name: Archive Jacoco reports
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: jacoco-reports
        path: results.csv
